apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbot
  labels:
    app: microbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microbot
  template:
    metadata:
      labels:
        app: microbot
    spec:
      containers:
      - name: microbot
        image: localhost:32000/microbot:local
        ports:
        - containerPort: 80
      nodeSelector:
        use: worker
---
apiVersion: v1
kind: Service
metadata:
  name: microbot
spec:
  selector:
    app: microbot
  ports:
    - protocol: TCP
      port: 80
      name: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microbot
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging" # use staging endpoint
    # cert-manager.io/cluster-issuer: "letsencrypt-prod" # use prod endpoint
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
    - example.domain.org
    # OR - example.org
    secretName: example-tls
  rules:
    - host: example.domain.org
    # OR - host: example.org
      http:
        paths:
        - path: /
          backend:
            serviceName: microbot
            servicePort: web
