FROM linuxserver/jellyfin:latest

RUN apt update && apt -y install language-pack-zh* fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core intel-media-va-driver-non-fre
