FROM ubuntu

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      tzdata apt-utils sudo && rm -rf /var/lib/apt/lists/*

COPY . /root/setup
WORKDIR /root/setup
RUN /root/setup/setup_ubuntu.sh

CMD ["/root/setup/test.sh"]
